#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
ALTER ROLE amend_owner WITH BYPASSRLS;
CREATE ROLE amend_app LOGIN PASSWORD '${AMEND_APP_PASSWORD}' NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO amend_app;
GRANT USAGE ON SCHEMA public TO amend_app;
EOSQL
