export const AUDIT_ACTIONS = [
  "login_success",
  "login_failure",
  "password_reset_requested",
  "password_reset_completed",
  "mfa_enrolled",
  "mfa_challenge_failed",
  "session_revoked",
  "logout",
  "invitation_sent",
  "invitation_accepted",
  "invitation_expired",
  "invitation_revoked",
  "registration_submitted",
  "registration_approved",
  "registration_denied",
  "account_deactivated",
  "account_reactivated",
  "account_hard_deleted",
  "role_assigned",
  "role_changed",
  "resource_created",
  "resource_edited",
  "resource_deleted",
  "resource_downloaded",
  "event_created",
  "event_edited",
  "event_cancelled",
  "event_rsvp",
  "announcement_created",
  "announcement_edited",
  "announcement_deleted",
  "post_created",
  "post_edited",
  "post_flagged",
  "post_hidden",
  "post_deleted",
  "thread_locked",
  "thread_pinned",
  "thread_deleted",
  "user_forum_suspended",
  "directory_privacy_changed",
  "directory_profile_viewed",
  "audit_log_viewed",
  "audit_log_exported",
  "bulk_invite_sent",
  "system_setting_changed",
  "retention_purged",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
export type AuditSeverity = "info" | "warning" | "security";
